# -*- coding: utf-8 -*-
"""Generate AorusEnvGuard.swift with no plaintext give-aways.

AorusEnvGuard is the integrity guard wired into the LICENSE path — it runs at the gate
and before every signed license request, so it is the detector that actually protects the
paid proxy. Yet it shipped every jailbreak path, tweak name and injection env var as a
plain string, so `strings | grep -i cydia` located it just like the old tamper guard did.

This regenerates it with the SAME logic (cross-API stat/access consistency, symlink and
sandbox-escape probes) but with every indicator XOR-obfuscated and the private probe
methods renamed to neutral names. It uses its OWN pad, distinct from gen_tamper_guard.py,
so a breakpoint on one detector's deobfuscator does not dump the other's strings.

Preserved verbatim, because they are external contracts:
  * the public API (denyDebuggerAttach / enforceAtLaunch / enforceAtGate /
    enforceBeforeRequest / flags), called from bootstrap, the gate and the API client;
  * the server flag values "jb" / "hook" / "dbg", which go into the signed request body;
  * the opaque UserDefaults keys and the accumulator / notification wiring.

Run after editing this file:
    python3 scripts/gen_env_guard.py
"""
import pathlib

OUT = pathlib.Path("AorusGram/Sources/Features/Subscription/AorusEnvGuard.swift")

# Distinct pad from the tamper guard.
KEY = bytes([0xE2, 0x7C, 0x91, 0x4D, 0xAF, 0x38, 0x60, 0xD5, 0x1B, 0xC4, 0x0A, 0x7E, 0x93, 0x26, 0xB8, 0x5F])

PATHS = [
    "/Applications/Cydia.app", "/Applications/Sileo.app", "/Applications/Zebra.app",
    "/Applications/Filza.app", "/Applications/blackra1n.app",
    "/usr/sbin/sshd", "/usr/bin/ssh", "/bin/bash", "/bin/sh", "/etc/apt",
    "/private/var/lib/apt", "/private/var/lib/cydia", "/private/var/stash",
    "/private/var/tmp/cydia.log", "/usr/libexec/cydia", "/usr/libexec/sftp-server",
    "/usr/lib/libsubstrate.dylib", "/usr/lib/libhooker.dylib", "/usr/lib/substitute-loader.dylib",
    "/Library/MobileSubstrate/MobileSubstrate.dylib", "/Library/MobileSubstrate/DynamicLibraries",
    "/var/jb", "/var/binpack", "/var/checkra1n.dmg",
]
MARKERS = [
    "substrate", "substitute", "libhooker", "frida", "cynject",
    "cycript", "rocketbootstrap", "shadow.dylib", "tweakinject",
    "libellekit", "pspawn",
]
SYMLINKS = ["/Applications", "/Library/Ringtones", "/Library/Wallpaper", "/usr/share", "/var/stash"]
SANDBOX_PREFIXES = ["/private/.age_", "/.age_"]
PTRACE = "ptrace"
INJECT_ENV = "DYLD_INSERT_LIBRARIES"


def obf(s: str) -> str:
    xored = [b ^ KEY[i % len(KEY)] for i, b in enumerate(s.encode("utf-8"))]
    return "[" + ", ".join("0x%02x" % b for b in xored) + "]"


def arr(name, items):
    out = [f"    private static let {name}: [[UInt8]] = ["]
    for it in items:
        out.append(f"        {obf(it)},")
    out.append("    ]")
    return "\n".join(out)


def build():
    pad = ", ".join("0x%02x" % b for b in KEY)
    return f'''import Foundation
import Darwin
import MachO

// Hardened runtime guard for the license layer.
//
// AUDIENCE: AorusGram ships via E-sign / AltStore sideloading — legitimate users are not
// running instrumented devices, so an injection / escaped-sandbox signal is, in practice,
// an attacker. That lets us deny protected operations on detection without crashing a
// legitimate client on a false positive.
//
// Every indicator below is obfuscated: nothing here appears in the binary's string table,
// so the guard cannot be located by scanning for a known path or tweak name. GENERATED by
// scripts/gen_env_guard.py — do not hand-edit.
//
// Cost-to-bypass is maximised by low-level syscalls (stat/access/lstat/getenv), not
// Foundation which bypass tweaks hook first; by cross-API consistency (Foundation says
// absent, a raw syscall says present → a tweak is selectively lying → detection); by
// multiple independent enforcement sites; and by re-checks at launch, at the gate and
// before every signed request. Detection denies rather than crashes.
enum AorusEnvGuard {{

    #if targetEnvironment(simulator)
    private static let isSimulator = true
    #else
    private static let isSimulator = false
    #endif

    private static let pad: [UInt8] = [{pad}]

    private static func s(_ b: [UInt8]) -> String {{
        var out = [UInt8]()
        out.reserveCapacity(b.count)
        for (i, v) in b.enumerated() {{ out.append(v ^ pad[i % pad.count]) }}
        return String(decoding: out, as: UTF8.self)
    }}

{arr("markerData", PATHS)}

{arr("imageData", MARKERS)}

{arr("linkData", SYMLINKS)}

{arr("probeData", SANDBOX_PREFIXES)}

    private static let ptraceSym: [UInt8] = {obf(PTRACE)}
    private static let injectEnv: [UInt8] = {obf(INJECT_ENV)}

    // MARK: - Public enforcement

    @discardableResult
    @inline(__always)
    static func enforceAtLaunch() -> Bool {{
        guard !isSimulator else {{ return true }}
        return recordIfCompromised(probeEnvironment(full: true))
    }}

    @discardableResult
    @inline(__always)
    static func enforceAtGate() -> Bool {{
        guard !isSimulator else {{ return true }}
        return recordIfCompromised(probeEnvironment(full: true))
    }}

    @discardableResult
    @inline(__always)
    static func enforceBeforeRequest() -> Bool {{
        guard !isSimulator else {{ return true }}
        return recordIfCompromised(probeImages() || probePaths() || probeSandbox())
    }}

    private static func recordIfCompromised(_ compromised: Bool) -> Bool {{
        guard compromised else {{ return true }}
        let defaults = UserDefaults.standard
        let wasRecorded = defaults.bool(forKey: "e7b3f014-2a8d-4c61-9f05-3b6a1e8d4c02")
        defaults.set(true, forKey: "c0a8b1e2-6f4d-4a9c-b3e7-1d520f8a6b34")
        defaults.set(true, forKey: "e7b3f014-2a8d-4c61-9f05-3b6a1e8d4c02")
        guard !wasRecorded else {{ return false }}
        AorusSessionCounter.shared.increment()
        NotificationCenter.default.post(
            name: NSNotification.Name("aorusgram.environmentCompromised"), object: nil
        )
        return false
    }}

    // MARK: - Anti-debug

    static func denyDebuggerAttach() {{
        typealias PtraceFn = @convention(c) (Int32, pid_t, UnsafeMutableRawPointer?, Int32) -> Int32
        let ptDenyAttach: Int32 = 31
        guard let handle = dlopen(nil, RTLD_NOW), let sym = dlsym(handle, s(Self.ptraceSym)) else {{ return }}
        let call = unsafeBitCast(sym, to: PtraceFn.self)
        _ = call(ptDenyAttach, 0, nil, 0)
    }}

    private static func probeTrace() -> Bool {{
        var info = kinfo_proc()
        var size = MemoryLayout<kinfo_proc>.stride
        var mib: [Int32] = [CTL_KERN, KERN_PROC, KERN_PROC_PID, getpid()]
        let result = mib.withUnsafeMutableBufferPointer {{ sysctl($0.baseAddress, 4, &info, &size, nil, 0) }}
        guard result == 0 else {{ return false }}
        let pTraced: Int32 = 0x00000800 // P_TRACED
        return (info.kp_proc.p_flag & pTraced) != 0
    }}

    // MARK: - Combined signal for the server (signed request body)

    static func flags() -> [String] {{
        guard !isSimulator else {{ return [] }}
        var flags: [String] = []
        if probePaths() || probeSandbox() || probeLinks() {{ flags.append("jb") }}
        if probeImages() {{ flags.append("hook") }}
        if probeTrace() {{ flags.append("dbg") }}
        return flags
    }}

    // MARK: - Detection core

    private static func probeEnvironment(full: Bool) -> Bool {{
        if probeImages() {{ return true }}
        if probePaths() {{ return true }}
        if probeSandbox() {{ return true }}
        if full && probeLinks() {{ return true }}
        if full && probeInjectEnv() {{ return true }}
        return false
    }}

    private static func probePaths() -> Bool {{
        for data in markerData {{
            let path = s(data)
            if FileManager.default.fileExists(atPath: path) || rawExists(path) {{ return true }}
        }}
        return false
    }}

    private static func rawExists(_ path: String) -> Bool {{
        if access(path, F_OK) == 0 {{ return true }}
        var st = stat()
        return stat(path, &st) == 0
    }}

    private static func probeSandbox() -> Bool {{
        for data in probeData {{
            let target = s(data) + String(UInt32.random(in: 0..<UInt32.max))
            if let file = fopen(target, "w") {{
                fclose(file)
                unlink(target)
                return true
            }}
        }}
        return false
    }}

    private static func probeImages() -> Bool {{
        let markers = imageData.map {{ s($0) }}
        let count = _dyld_image_count()
        var i: UInt32 = 0
        while i < count {{
            if let cName = _dyld_get_image_name(i) {{
                let name = String(cString: cName).lowercased()
                if markers.contains(where: {{ name.contains($0) }}) {{ return true }}
            }}
            i += 1
        }}
        return false
    }}

    private static func probeInjectEnv() -> Bool {{
        return getenv(s(Self.injectEnv)) != nil
    }}

    private static func probeLinks() -> Bool {{
        for data in linkData {{
            var st = stat()
            if lstat(s(data), &st) == 0 && (UInt32(st.st_mode) & UInt32(S_IFMT)) == UInt32(S_IFLNK) {{ return true }}
        }}
        return false
    }}
}}
'''


def main():
    OUT.write_text(build(), encoding="utf-8")
    print(f"{OUT}: {len(build())} bytes")


if __name__ == "__main__":
    main()
