# -*- coding: utf-8 -*-
"""Generate AorusTamperGuard.swift with no plaintext give-aways.

The previous version shipped every jailbreak indicator as a plain string literal —
"/Applications/Cydia.app", "frida", "hook framework: …" — and a human-readable
authorship watermark. `strings binary | grep -i cydia` located the whole protection
in one line, which is exactly how it was defeated. It also embedded the build's
author line in cleartext.

This generator emits the same checks with:
  * every sensitive path, dylib name and symbol XOR-obfuscated into a byte array,
    so none of them appear in the binary's string table;
  * opaque integer codes instead of descriptive flag messages, so the log strings
    carry no hint of what tripped;
  * no watermark string at all.

Two byte-identical copies are written — one per module (AorusGram, AorusGramUI) —
because the two modules each compile their own. scripts/verify_aorus_branding.py
checks both exist and match.

Run after editing this file:
    python3 scripts/gen_tamper_guard.py
"""
import pathlib

# Fixed multi-byte XOR key. The point is not secrecy of the key — a determined
# reverser can recover it — but to defeat the trivial `strings | grep` that found
# the old version. Keeping it fixed keeps both copies byte-identical and the output
# stable across regenerations.
KEY = bytes([0x5B, 0xA6, 0x3D, 0xF1, 0x74, 0x92, 0xC8, 0x0E, 0x21, 0xBD, 0x6F, 0x4A, 0x17, 0xE3, 0x88, 0x5C])

OUTPUTS = [
    pathlib.Path("AorusGram/Sources/Security/AorusTamperGuard.swift"),
    pathlib.Path("patches/submodules/AorusGramUI/Sources/Security/AorusTamperGuard.swift"),
]

# Sensitive literals, grouped. Each becomes an obfuscated byte array in Swift.
JB_PATHS = [
    "/Applications/Cydia.app",
    "/Library/MobileSubstrate/MobileSubstrate.dylib",
    "/bin/bash",
    "/usr/sbin/sshd",
    "/etc/apt",
    "/private/var/lib/apt/",
    "/private/var/jb",
]
HOOK_PATHS = [
    "/usr/lib/TweakInject",
    "/usr/lib/libsubstitute.dylib",
    "/usr/lib/libhooker.dylib",
    "/usr/lib/ellekit.dylib",
    "/Library/MobileSubstrate/DynamicLibraries",
]
DYLIB_SUSPECTS = [
    "frida", "gadget", "cynject", "substrate", "substitute", "cycript",
    "libhooker", "ellekit", "tweakinject", "blackjack",
]
DYLD_ENV = ["DYLD_INSERT_LIBRARIES", "DYLD_LIBRARY_PATH", "DYLD_FRAMEWORK_PATH"]
SANDBOX_PREFIX = "/private/.ag_"   # write-probe path prefix (was /private/jb_test_ag_)
SYSTEM_PREFIXES = ["/System/", "/usr/lib/", "/private/preboot/"]
BUNDLE_ALLOWED = ["ph.telegra.Telegraph", "aorusgram", "com.aorusgram"]
PTRACE = "ptrace"
FRIDA_LOOPBACK = "127.0.0.1"
# UserDefaults keys are duplicated from their canonical definitions; the cross-module
# mirror still needs the literal value, but it no longer sits in cleartext.
UD_FRIDA = "c0a8b1e2-6f4d-4a9c-b3e7-1d520f8a6b34"  # opaque mirror flag; was _ag_frida (telltale)


def obf(s: str) -> str:
    data = s.encode("utf-8")
    xored = [b ^ KEY[i % len(KEY)] for i, b in enumerate(data)]
    return "[" + ", ".join("0x%02x" % b for b in xored) + "]"


def obf_list(name, items):
    lines = [f"    private static let {name}: [[UInt8]] = ["]
    for it in items:
        lines.append(f"        {obf(it)},")
    lines.append("    ]")
    return "\n".join(lines)


def build(full: bool) -> str:
    key_literal = ", ".join("0x%02x" % b for b in KEY)
    parts = []
    parts.append('''import Foundation
import UIKit
import Darwin
import MachO
import ObjectiveC

// Runtime integrity checks run once at bootstrap. Every indicator string is
// obfuscated: nothing here appears in the binary's string table, so the checks
// cannot be located by scanning for a known jailbreak path or framework name.
//
// GENERATED by scripts/gen_tamper_guard.py — do not hand-edit. Two byte-identical
// copies exist, one per module.
//
// Detections are non-fatal on purpose: a hard crash on a check is trivial to locate
// and patch, and risks bricking a false positive. Instead every hit feeds the
// distributed accumulator, whose delayed, indirect reaction drives the license gate.

public final class AorusSessionMetrics {
    public static let shared = AorusSessionMetrics()
    private init() {}

    public static var metricFlag: Bool = false

    // Opaque XOR pad. Not a secret — it exists to defeat plain-string scanning.''')
    parts.append(f"    private static let pad: [UInt8] = [{key_literal}]")
    parts.append('''
    private static func s(_ b: [UInt8]) -> String {
        var out = [UInt8]()
        out.reserveCapacity(b.count)
        for (i, v) in b.enumerated() {
            out.append(v ^ pad[i % pad.count])
        }
        return String(decoding: out, as: UTF8.self)
    }
''')
    parts.append(obf_list("jbPaths", JB_PATHS))
    parts.append("")
    parts.append(obf_list("hookPaths", HOOK_PATHS))
    parts.append("")
    parts.append(obf_list("dylibSuspects", DYLIB_SUSPECTS))
    parts.append("")
    parts.append(obf_list("dyldEnv", DYLD_ENV))
    parts.append("")
    parts.append(obf_list("systemPrefixes", SYSTEM_PREFIXES))
    parts.append("")
    parts.append(obf_list("bundleAllowed", BUNDLE_ALLOWED))
    parts.append("")
    parts.append(f"    private static let sandboxPrefix: [UInt8] = {obf(SANDBOX_PREFIX)}")
    parts.append(f"    private static let ptraceSym: [UInt8] = {obf(PTRACE)}")
    parts.append(f"    private static let loopback: [UInt8] = {obf(FRIDA_LOOPBACK)}")
    parts.append(f"    private static let mirrorKey: [UInt8] = {obf(UD_FRIDA)}")
    parts.append('''
    // MARK: - Run all checks

    public func collect() {
        sampleTrace()
        sampleBundle()
        sampleStorage()
        sampleModules()
        sampleFrameworks()
        sampleBindings()
        sampleAttach()
        samplePort()
    }

    private func sampleBundle() {
        guard let bundleId = Bundle.main.bundleIdentifier?.lowercased() else {
            flag(1); return
        }
        let allowed = Self.bundleAllowed.map { Self.s($0).lowercased() }
        if !allowed.contains(where: { bundleId.contains($0) }) {
            flag(2)
        }
    }

    private func sampleStorage() {
        #if targetEnvironment(simulator)
        return
        #else
        for p in Self.jbPaths where FileManager.default.fileExists(atPath: Self.s(p)) {
            flag(3); return
        }
        let testPath = Self.s(Self.sandboxPrefix) + String(arc4random())
        do {
            try "t".write(toFile: testPath, atomically: true, encoding: .utf8)
            try FileManager.default.removeItem(atPath: testPath)
            flag(4)
        } catch {}
        #endif
    }

    private func sampleModules() {
        let env = ProcessInfo.processInfo.environment
        for key in Self.dyldEnv {
            if let val = env[Self.s(key)], !val.isEmpty {
                mark(); flag(5); return
            }
        }
        let count = _dyld_image_count()
        let suspects = Self.dylibSuspects.map { Self.s($0) }
        for i in 0..<count {
            guard let raw = _dyld_get_image_name(i) else { continue }
            let name = String(cString: raw).lowercased()
            if suspects.contains(where: { name.contains($0) }) {
                mark(); flag(6); return
            }
        }
    }

    private func sampleFrameworks() {
        #if !targetEnvironment(simulator)
        for p in Self.hookPaths where FileManager.default.fileExists(atPath: Self.s(p)) {
            mark(); flag(7); return
        }
        #endif
    }

    private func sampleBindings() {
        #if !targetEnvironment(simulator)
        let pairs: [(String, String)] = [
            ("NSUserDefaults", "boolForKey:"),
            ("NSFileManager",  "fileExistsAtPath:"),
            ("NSProcessInfo",  "environment"),
        ]
        let prefixes = Self.systemPrefixes.map { Self.s($0) }
        for (clsName, selName) in pairs {
            guard let cls = objc_getClass(clsName) as? AnyClass,
                  let m = class_getInstanceMethod(cls, Selector((selName))) else { continue }
            let imp = method_getImplementation(m)
            let ptr = unsafeBitCast(imp, to: UnsafeRawPointer.self)
            var info = Dl_info()
            guard dladdr(ptr, &info) != 0, let fname = info.dli_fname else {
                mark(); flag(8); return
            }
            let lib = String(cString: fname)
            if !prefixes.contains(where: { lib.hasPrefix($0) }) {
                mark(); flag(9); return
            }
        }
        #endif
    }

    private func sampleTrace() {
        #if !targetEnvironment(simulator)
        typealias PtraceT = @convention(c) (CInt, CInt, CInt, CInt) -> CInt
        let handle = dlopen(nil, RTLD_LAZY)
        if let sym = dlsym(handle, Self.s(Self.ptraceSym)) {
            _ = unsafeBitCast(sym, to: PtraceT.self)(31, 0, 0, 0)
        }
        dlclose(handle)
        #endif
    }

    private func sampleAttach() {
        #if !targetEnvironment(simulator)
        var info = kinfo_proc()
        var size = MemoryLayout<kinfo_proc>.size
        var mib: [CInt] = [CTL_KERN, KERN_PROC, KERN_PROC_PID, getpid()]
        sysctl(&mib, 4, &info, &size, nil, 0)
        if info.kp_proc.p_flag & P_TRACED != 0 {
            mark(); flag(10)
        }
        #endif
    }

    private func samplePort() {
        #if !targetEnvironment(simulator)
        DispatchQueue.global(qos: .background).async { [weak self] in
            var addr = sockaddr_in()
            addr.sin_family = sa_family_t(AF_INET)
            addr.sin_port = CFSwapInt16HostToBig(27042)
            addr.sin_addr.s_addr = inet_addr(Self.s(Self.loopback))
            let sock = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)
            guard sock >= 0 else { return }
            defer { close(sock) }
            var tv = timeval(tv_sec: 0, tv_usec: 300_000)
            setsockopt(sock, SOL_SOCKET, SO_SNDTIMEO, &tv, socklen_t(MemoryLayout<timeval>.size))
            setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, &tv, socklen_t(MemoryLayout<timeval>.size))
            let ok = withUnsafePointer(to: &addr) {
                $0.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                    connect(sock, $0, socklen_t(MemoryLayout<sockaddr_in>.size))
                }
            }
            if ok == 0 {
                self?.mark(); self?.flag(11)
            }
        }
        #endif
    }

    private func mark() {
        AorusSessionMetrics.metricFlag = true
        UserDefaults.standard.set(true, forKey: Self.s(Self.mirrorKey))
    }

    // Opaque code, no descriptive text.__FLAG_DOC__
    private func flag(_ code: Int) {
__FLAG_BODY__        NotificationCenter.default.post(name: .aorusMetricSignal, object: code)
    }
}

extension Notification.Name {
    public static let aorusMetricSignal: Notification.Name = {
        let b: [UInt8] = [0x70,0x4D,0x41,0x31,0x26,0x01,0x05,0xE9,0xF4,0xF5,0xCF,0xAD,0xB0,0x9E,0x9A,0x63,0x7D,0x57,0x21,0x21,0x03,0x14,0xFC,0xFC,0xCE]
        let m: [UInt8] = [0x11,0x22,0x33,0x44,0x55,0x66,0x77,0x88,0x99,0xAA,0xBB,0xCC,0xDD,0xEE,0xFF,0x11,0x22,0x33,0x44,0x55,0x66,0x77,0x88,0x99,0xAA]
        return Notification.Name(String(bytes: zip(b, m).map { $0 ^ $1 }, encoding: .utf8)!)
    }()
}''')
    swift = "\n".join(parts) + "\n"
    if full:
        swift = swift.replace(
            "__FLAG_DOC__",
            " Feeds the distributed accumulator; no single\n    // patched check can stop the threshold being reached by the others.",
        )
        swift = swift.replace("__FLAG_BODY__", "        AorusSessionCounter.shared.increment()\n")
    else:
        # AorusGramUI has no accumulator; it signals only through the cross-module flag.
        swift = swift.replace("__FLAG_DOC__", " Cross-module hits travel via the mirrored flag.")
        swift = swift.replace("__FLAG_BODY__", "")
    return swift


def main():
    variants = {
        OUTPUTS[0]: True,   # AorusGram module — has the accumulator
        OUTPUTS[1]: False,  # AorusGramUI module — no accumulator, mirrors via UserDefaults
    }
    for out, full in variants.items():
        swift = build(full)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(swift, encoding="utf-8")
        print(f"{out}: {len(swift)} bytes (full={full})")


if __name__ == "__main__":
    main()
