import Foundation
import ObjectiveC

private func aorusLicenseLocked() -> Bool {
    UserDefaults.standard.bool(forKey: "aorusgram_license_locked")
}

// Ghost Mode: blocks outgoing online presence, read receipts, and typing indicators.
// Works via two complementary layers:
//   1. MTRequestMessageService ObjC swizzle — intercepts serialised MTProto requests
//      BEFORE they leave the process and drops ghost-mode-irrelevant ones.
//   2. UserDefaults flag "aorusgram_ghost_mode" — read by branding.py-injected guards
//      inside AccountStateManager / AccountPresenceManager source patches.
final class GhostModeManager {
    static let shared = GhostModeManager()
    private init() {}

    private(set) var isEnabled: Bool = false {
        didSet {
            let effective = aorusLicenseLocked() ? false : isEnabled
            UserDefaults.standard.set(effective, forKey: "aorusgram_ghost_mode")
            NotificationCenter.default.post(name: .ghostModeChanged, object: effective)
        }
    }

    private(set) var hideLastSeen: Bool = true
    private(set) var blockReadReceipts: Bool = true
    private(set) var hidePeekStatus: Bool = true

    func load() {
        isEnabled = aorusLicenseLocked() ? false : UserDefaults.standard.bool(forKey: "aorusgram_ghost_mode")
    }

    func toggle() { setEnabled(!isEnabled) }

    func setEnabled(_ value: Bool) { isEnabled = aorusLicenseLocked() ? false : value }

    func configure(hideLastSeen: Bool, blockReadReceipts: Bool, hidePeekStatus: Bool) {
        self.hideLastSeen = hideLastSeen
        self.blockReadReceipts = blockReadReceipts
        self.hidePeekStatus = hidePeekStatus
        UserDefaults.standard.set(hideLastSeen,     forKey: "aorusgram_ghost_hide_last_seen")
        UserDefaults.standard.set(blockReadReceipts, forKey: "aorusgram_ghost_block_read")
        UserDefaults.standard.set(hidePeekStatus,   forKey: "aorusgram_ghost_hide_typing")
    }

    func shouldSendOnlinePresence() -> Bool  { aorusLicenseLocked() ? true : !isEnabled }
    func shouldSendReadReceipt(peerId: Int64) -> Bool {
        guard !aorusLicenseLocked() else { return true }
        guard isEnabled else { return true }
        return !UserDefaults.standard.bool(forKey: "aorusgram_ghost_block_read")
    }
    func shouldSendTypingIndicator() -> Bool {
        guard !aorusLicenseLocked() else { return true }
        guard isEnabled else { return true }
        return !UserDefaults.standard.bool(forKey: "aorusgram_ghost_hide_typing")
    }
}

extension Notification.Name {
    static let ghostModeChanged = Notification.Name("aorusgram_ghost_mode_changed")
}

// MARK: - MTProto-level request interceptor (ObjC runtime — works because MtProtoKit is ObjC)

// TL constructor IDs for requests blocked in ghost mode (little-endian UInt32 matching TL schema):
//   account.updateStatus  #6628562c
//   messages.setTyping    #58943ee2
//   messages.readHistory  #0e306d3a  (older clients)
//   messages.readMessageContents #36a73f77
private let kGhostBlockedConstructors: Set<UInt32> = [
    0x6628562c,
    0x58943ee2,
    0x0e306d3a,
    0x36a73f77,
]

// NSObject category installed on MTRequestMessageService at runtime.
// After swizzle:
//   MTRequestMessageService.addRequest:  →  _aorusGhost_addRequest:  (our code below)
//   NSObject._aorusGhost_addRequest:     →  original addRequest: implementation
// Calling self._aorusGhost_addRequest() from inside _aorusGhost_addRequest therefore
// calls the original — the standard ObjC swizzle-with-call-through pattern.
// Ghost-mode keywords in the class name / description of MTRequest body objects.
// MtProtoKit TL-generated ObjC classes follow patterns like:
//   TL_account_updateStatus, TLaccount_updateStatus, Api_functions_account_updateStatus
// Swift-generated wrappers bridged to ObjC may have mangled names containing:
//   "updateStatus", "setTyping", "readHistory", "readMessageContents"
private let kGhostBlockedKeywords: [String] = [
    "updateStatus",       // account.updateStatus  — online/offline
    "setTyping",          // messages.setTyping    — typing indicator
    "readHistory",        // messages.readHistory  — read receipts (older API)
    "readMessageContents",// messages.readMessageContents
]

private extension NSObject {
    @objc func _aorusGhost_addRequest(_ request: AnyObject) {
        if !aorusLicenseLocked() && UserDefaults.standard.bool(forKey: "aorusgram_ghost_mode") {
            // Layer 1: inspect body class name. MtProtoKit's MTRequest.body is the
            // MTSerializableObject TL wrapper (Swift type generated by TelegramApi).
            // The Swift type name is mangled but ALWAYS contains the TL function name
            // (e.g. "...account12updateStatus..." for account.updateStatus).
            if let body = request.value(forKey: "body") {
                let className = NSStringFromClass(type(of: body as AnyObject))
                if kGhostBlockedKeywords.contains(where: { className.contains($0) }) {
                    print("[GhostMode] blocked by class name: \(className)")
                    return
                }
                let desc = String(describing: body)
                if kGhostBlockedKeywords.contains(where: { desc.contains($0) }) {
                    print("[GhostMode] blocked by description: \(desc.prefix(80))")
                    return
                }
            }

            // Layer 2: binary TL constructor ID from MTBuffer-backed serialized bytes.
            // MTRequest stores serialized bytes as either:
            //   - MTRequest.serializedBody (MTBuffer; has .data NSData)
            //   - directly under property names varying by MtProtoKit version
            if let bytes = Self._aorusGhost_extractBytes(from: request), bytes.count >= 4 {
                let c = bytes.withUnsafeBytes { $0.load(as: UInt32.self) }
                if kGhostBlockedConstructors.contains(c) {
                    print(String(format: "[GhostMode] blocked by constructor ID: 0x%08x", c))
                    return
                }
            }
        }
        self._aorusGhost_addRequest(request) // call original
    }

    /// Try every property name MtProtoKit uses across versions to expose serialized bytes.
    /// Returns the first valid NSData/Data found (4+ bytes).
    static func _aorusGhost_extractBytes(from request: AnyObject) -> Data? {
        // Direct Data-bearing keys
        let directKeys = ["serializedBody", "bodyData", "payload", "rawData", "serializedData"]
        for key in directKeys {
            if let v = request.value(forKey: key) {
                if let d = v as? Data, d.count >= 4 { return d }
                // MTBuffer wrapper — has .data NSData
                if let buf = v as? NSObject, let inner = buf.value(forKey: "data") as? Data, inner.count >= 4 {
                    return inner
                }
            }
        }
        // Fallback: ask the body object to serialize itself
        if let body = request.value(forKey: "body") as? NSObject {
            // Try MTBuffer-returning serialize on the body
            let sel = NSSelectorFromString("serialize")
            if body.responds(to: sel),
               let bufferRef = body.perform(sel),
               let buffer = bufferRef.takeUnretainedValue() as? NSObject,
               let d = buffer.value(forKey: "data") as? Data, d.count >= 4 {
                return d
            }
        }
        return nil
    }
}

final class GhostModeSwizzler {
    static func apply() {
        guard let cls = NSClassFromString("MTRequestMessageService") else {
            print("[GhostMode] MTRequestMessageService not found — MTProto layer swizzle skipped")
            return
        }
        let original   = NSSelectorFromString("addRequest:")
        let replacement = #selector(NSObject._aorusGhost_addRequest(_:))

        guard
            let origMethod = class_getInstanceMethod(cls, original),
            let repMethod  = class_getInstanceMethod(NSObject.self, replacement)
        else { return }

        // Install our method on the target class, then swap implementations.
        let added = class_addMethod(cls, replacement,
                                    method_getImplementation(repMethod),
                                    method_getTypeEncoding(repMethod))
        if added {
            guard let installed = class_getInstanceMethod(cls, replacement) else { return }
            method_exchangeImplementations(origMethod, installed)
            print("[GhostMode] MTRequestMessageService.addRequest swizzled — presence/typing/read blocked")
        } else {
            method_exchangeImplementations(origMethod, repMethod)
        }
    }
}
